version: "3.7"
services:
  system-prune:
    image: docker:latest
    command: docker system prune --all --force
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      restart_policy:
        delay: 24h
