language: bash

services:
  - docker

stages:
  - name: deploy
    if: tag IS present

jobs:
  include:
    - script:
        - make pull || true
        - make
    - stage: deploy
      script: make push
