version: "3.7"
services:
  buildbot:
    image: cjolowicz/buildbot:2.1.0
    init: true
    ports:
      - "8010:8010"
      - "9989:9989"
    volumes:
      - buildbot:/var/lib/buildbot
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      BUILDBOT_URL:
    configs:
      - source: master.cfg
        target: /etc/buildbot/master.cfg
    deploy:
      placement:
        constraints: [node.role == manager]
    logging:
      options:
        max-size: "10m"
        max-file: "10"
volumes:
  buildbot:
configs:
  master.cfg:
    file: buildbot/master.cfg
    name: buildbot-master-cfg-${BUILDBOT_MASTER_CFG_HASH:?BUILDBOT_MASTER_CFG_HASH}
