version: "3.7"
services:
  buildbot:
    image: cjolowicz/buildbot:1.8.0
    init: true
    ports:
      - "8010:8010"
    volumes:
      - buildbot:/var/lib/buildbot
      - /home/docker/.docker:/var/lib/buildbot/.docker
    environment:
      DOCKER_HOST:
      DOCKER_TLS_VERIFY:
      DOCKER_CERT_PATH: /run/secrets
    configs:
      - source: master.cfg
        target: /var/lib/buildbot/master.cfg
    secrets:
      - ca.pem
      - cert.pem
      - key.pem
    deploy:
      placement:
        constraints: [node.role == manager]
    logging:
      options:
        max-size: "10m"
        max-file: "10"
volumes:
  buildbot:
secrets:
  ca.pem:
    file: $HOME/.docker/machine/certs/ca.pem
  cert.pem:
    file: $HOME/.docker/machine/certs/cert.pem
  key.pem:
    file: $HOME/.docker/machine/certs/key.pem
configs:
  master.cfg:
    file: ./master.cfg
    name: buildbot-master-cfg-${BUILDBOT_MASTER_CFG_HASH:?BUILDBOT_MASTER_CFG_HASH}
