version: "3.7"
services:
  buildbot:
    image: cjolowicz/buildbot:1.8.1
    init: true
    ports:
      - "8010:8010"
      - "9989:9989"
    volumes:
      - buildbot:/var/lib/buildbot
      - ./buildbot/master.cfg:/etc/buildbot/master.cfg
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      options:
        max-size: "10m"
        max-file: "10"
volumes:
  buildbot:
