version: "3.7"
services:
  buildbot:
    image: cjolowicz/buildbot:1.8.0
    init: true
    ports:
      - "8010:8010"
    volumes:
      - buildbot:/var/lib/buildbot
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_HOST:
      DOCKER_TLS_VERIFY:
      DOCKER_CERT_PATH:
    logging:
      options:
        max-size: "10m"
        max-file: "10"
volumes:
  buildbot:
