version: "3.7"
services:
  buildbot:
    image: cjolowicz/buildbot:1.8.0
    init: true
    ports:
      - "8010:8010"
    volumes:
      - buildbot:/var/lib/buildbot
      - /home/docker/.docker:/var/lib/buildbot/.docker
    environment:
      DOCKER_HOST:
      DOCKER_TLS_VERIFY:
    deploy:
      placement:
        constraints: [node.role == manager]
    logging:
      options:
        max-size: "10m"
        max-file: "10"
volumes:
  buildbot:
